### ISSUE TITLE
reinstate boot2docker support

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/zfs-builder#1]
[minishift](https://github.com/minishift/minishift), which we possibly want to support (and which is based on minikube, which we probably want to support as well), uses
```
Boot2Docker version 1.12.6, build HEAD : 5ab2289 - Wed Jan 11 03:20:40 UTC 2017
```

dig out the boot2docker support from the repo history, and make it work for
```
Linux minishift 4.4.41-boot2docker #1 SMP Wed Jan 11 03:05:24 UTC 2017 x86_64 GNU/Linux
```

**Comment by Godley** [comment]
Low prio, closing
